import { MovieEntity } from '@domain';

export const ListOfMoviesInstance: Array<MovieEntity> = [
  {
    adult: false,
    backdrop_path: '/sR0SpCrXamlIkYMdfz83sFn5JS6.jpg',
    genre_ids: [878, 28, 12],
    id: 823464,
    original_language: 'en',
    original_title: 'Godzilla x Kong: The New Empire',
    overview:
      'Following their explosive showdown, Godzilla and Kong must reunite against a colossal undiscovered threat hidden within our world, challenging their very existence – and our own.',
    popularity: 4500.758,
    poster_path: '/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    release_date: '2024-03-27',
    title: 'Godzilla x Kong: The New Empire',
    video: false,
    vote_average: 7.259,
    vote_count: 2038,
  },
  {
    adult: false,
    backdrop_path: '/q8IEFmEGGSGmAWfwRs23XDwdFN4.jpg',
    genre_ids: [878, 28, 12],
    id: 786892,
    original_language: 'en',
    original_title: 'Furiosa: A Mad Max Saga',
    overview:
      'As the world fell, young Furiosa is snatched from the Green Place of Many Mothers and falls into the hands of a great Biker Horde led by the Warlord Dementus. Sweeping through the Wasteland they come across the Citadel presided over by The Immortan Joe. While the two Tyrants war for dominance, Furiosa must survive many trials as she puts together the means to find her way home.',
    popularity: 1090.011,
    poster_path: '/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
    release_date: '2024-05-22',
    title: 'Furiosa: A Mad Max Saga',
    video: false,
    vote_average: 7.6,
    vote_count: 103,
  },
  {
    adult: false,
    backdrop_path: '/iafs5DG5fGq7ef0acl3xlX4BFrs.jpg',
    genre_ids: [18, 10770],
    id: 1219685,
    original_language: 'fr',
    original_title: 'Un père idéal',
    overview:
      'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.',
    popularity: 997.541,
    poster_path: '/4xJd3uwtL1vCuZgEfEc8JXI9Uyx.jpg',
    release_date: '2024-04-21',
    title: 'Un père idéal',
    video: false,
    vote_average: 6.4,
    vote_count: 25,
  },
  {
    adult: false,
    backdrop_path: '/rmNlWyez5cniGtXkgixG1ezdqVk.jpg',
    genre_ids: [28, 53],
    id: 1093995,
    original_language: 'en',
    original_title: 'Chief of Station',
    overview:
      'After learning that the death of his wife was not an accident, a former CIA Station Chief is forced back into the espionage underworld, teaming up with an adversary to unravel a conspiracy that challenges everything he thought he knew.',
    popularity: 661.04,
    poster_path: '/uuA01PTtPombRPvL9dvsBqOBJWm.jpg',
    release_date: '2024-05-02',
    title: 'Chief of Station',
    video: false,
    vote_average: 5.3,
    vote_count: 34,
  },
  {
    adult: false,
    backdrop_path: '/1jj4HXkx0pvEYhISYqktADYAITJ.jpg',
    genre_ids: [28, 35],
    id: 746036,
    original_language: 'en',
    original_title: 'The Fall Guy',
    overview:
      'Fresh off an almost career-ending accident, stuntman Colt Seavers has to track down a missing movie star, solve a conspiracy and try to win back the love of his life while still doing his day job.',
    popularity: 652.032,
    poster_path: '/tSz1qsmSJon0rqjHBxXZmrotuse.jpg',
    release_date: '2024-04-24',
    title: 'The Fall Guy',
    video: false,
    vote_average: 7.448,
    vote_count: 585,
  },
  {
    adult: false,
    backdrop_path: '/vWzJDjLPmycnQ42IppEjMpIhrhc.jpg',
    genre_ids: [16, 35, 10751],
    id: 748783,
    original_language: 'en',
    original_title: 'The Garfield Movie',
    overview:
      'Garfield, the world-famous, Monday-hating, lasagna-loving indoor cat, is about to have a wild outdoor adventure! After an unexpected reunion with his long-lost father – scruffy street cat Vic – Garfield and his canine friend Odie are forced from their perfectly pampered life into joining Vic in a hilarious, high-stakes heist.',
    popularity: 636.606,
    poster_path: '/zK2sFxZcelHJRPVr242rxy5VK4T.jpg',
    release_date: '2024-04-30',
    title: 'The Garfield Movie',
    video: false,
    vote_average: 6.5,
    vote_count: 92,
  },
  {
    adult: false,
    backdrop_path: '/wODqakS0jinTUECNS6n4VomQbew.jpg',
    genre_ids: [14, 12, 35],
    id: 967847,
    original_language: 'en',
    original_title: 'Ghostbusters: Frozen Empire',
    overview:
      'When the discovery of an ancient artifact unleashes an evil force, Ghostbusters new and old must join forces to protect their home and save the world from a second Ice Age.',
    popularity: 588.396,
    poster_path: '/e1J2oNzSBdou01sUvriVuoYp0pJ.jpg',
    release_date: '2024-03-20',
    title: 'Ghostbusters: Frozen Empire',
    video: false,
    vote_average: 6.679,
    vote_count: 826,
  },
  {
    adult: false,
    backdrop_path: '/4CcUgdiGe83MeqJW1NyJVmZqRrF.jpg',
    genre_ids: [10749, 18],
    id: 937287,
    original_language: 'en',
    original_title: 'Challengers',
    overview:
      'Tennis player turned coach Tashi has taken her husband, Art, and transformed him into a world-famous Grand Slam champion. To jolt him out of his recent losing streak, she signs him up for a "Challenger" event — close to the lowest level of pro tournament — where he finds himself standing across the net from his former best friend and Tashi\'s former boyfriend.',
    popularity: 544.946,
    poster_path: '/H6vke7zGiuLsz4v4RPeReb9rsv.jpg',
    release_date: '2024-04-18',
    title: 'Challengers',
    video: false,
    vote_average: 7.306,
    vote_count: 691,
  },
  {
    adult: false,
    backdrop_path: '/ySgY4jBvZ6qchrxKnBg4M8tZp8V.jpg',
    genre_ids: [27, 53],
    id: 1111873,
    original_language: 'en',
    original_title: 'Abigail',
    overview:
      'A group of criminals kidnaps a teenage ballet dancer, the daughter of a notorious gang leader, in order to obtain a ransom of $50 million, but over time, they discover that she is not just an ordinary girl. After the kidnappers begin to diminish, one by one, they discover, to their increasing horror, that they are locked inside with an unusual girl.',
    popularity: 525.755,
    poster_path: '/7qxG0zyt29BI0IzFDfsps62kbQi.jpg',
    release_date: '2024-04-18',
    title: 'Abigail',
    video: false,
    vote_average: 6.858,
    vote_count: 510,
  },
  {
    adult: false,
    backdrop_path: '/uv2twFGMk2qBdyJBJAVcrpRtSa9.jpg',
    genre_ids: [10752, 28, 18],
    id: 929590,
    original_language: 'en',
    original_title: 'Civil War',
    overview:
      'In the near future, a group of war journalists attempt to survive while reporting the truth as the United States stands on the brink of civil war.',
    popularity: 514.654,
    poster_path: '/sh7Rg8Er3tFcN9BpKIPOMvALgZd.jpg',
    release_date: '2024-04-10',
    title: 'Civil War',
    video: false,
    vote_average: 7.377,
    vote_count: 725,
  },
  {
    adult: false,
    backdrop_path: '/tpiqEVTLRz2Mq7eLq5DT8jSrp71.jpg',
    genre_ids: [878, 28, 18],
    id: 934632,
    original_language: 'en',
    original_title: 'Rebel Moon - Part Two: The Scargiver',
    overview:
      'The rebels gear up for battle against the ruthless forces of the Motherworld as unbreakable bonds are forged, heroes emerge — and legends are made.',
    popularity: 466.804,
    poster_path: '/cxevDYdeFkiixRShbObdwAHBZry.jpg',
    release_date: '2024-04-19',
    title: 'Rebel Moon - Part Two: The Scargiver',
    video: false,
    vote_average: 6.111,
    vote_count: 803,
  },
  {
    adult: false,
    backdrop_path: '/fOy2Jurz9k6RnJnMUMRDAgBwru2.jpg',
    genre_ids: [16, 10751, 35, 14],
    id: 508947,
    original_language: 'en',
    original_title: 'Turning Red',
    overview:
      'Thirteen-year-old Mei is experiencing the awkwardness of being a teenager with a twist – when she gets too excited, she transforms into a giant red panda.',
    popularity: 417.551,
    poster_path: '/qsdjk9oAKSQMWs0Vt5Pyfh6O4GZ.jpg',
    release_date: '2022-03-10',
    title: 'Turning Red',
    video: false,
    vote_average: 7.387,
    vote_count: 4955,
  },
];

export const MovieInstance: MovieEntity = ListOfMoviesInstance[0];
